### ISSUE TITLE
Suggestion: do not round boost multiplier, instead round the xp

### ISSUE THREAD

**Issue by dentatar** [Keurig-Creator/XPBooster#4]
Hello. As the title says wouldn't it be a better approach to round xp that player would get and allow using decimal multipliers? For example if i have a boost of 1.2x and got 7 xp it would be 8.4 so rounded to 8 etc. If it's ever get implemented like that it may be a good idea to add rounding options to the config to choose from floor/round/ceil. Thanks!
Also i know about full range option in the config, but it's confusing how it suppose to work… In my testing i got same results with it and without it.

**Comment by Keurig-Creator** [comment]
Since Minecraft's XP system works on whole numbers, it either needs to be rounded up or down, which is why the full range option doesn't do much, as stated in the comment section. This is actually a great idea.
